In [1]:
import pandas as pd
import numpy as np
import os

df = pd.read_csv('CSE-CIC-IDS2018.csv', low_memory=False)

In [2]:
df.head()

Dst Port  Protocol            Timestamp  Flow Duration  Tot Fwd Pkts  \
0         0         0  14/02/2018 08:31:01      112641719             3   
1         0         0  14/02/2018 08:33:50      112641466             3   
2         0         0  14/02/2018 08:36:39      112638623             3   
3        22         6  14/02/2018 08:40:13        6453966            15   
4        22         6  14/02/2018 08:40:23        8804066            14   

   Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  \
0             0                0                0                0   
1             0                0                0                0   
2             0                0                0                0   
3            10             1239             2273              744   
4            11             1143             2209              744   

   Fwd Pkt Len Min  ...  Fwd Seg Size Min  Active Mean  Active Std  \
0                0  ...                 0          0.0         0.0   
1                0  ...                 0          0.0         0.0   
2                0  ...                 0          0.0         0.0   
3                0  ...                32          0.0         0.0   
4                0  ...                32          0.0         0.0   

   Active Max  Active Min   Idle Mean    Idle Std  Idle Max  Idle Min   Label  
0           0           0  56320859.5  139.300036  56320958  56320761  Benign  
1           0           0  56320733.0  114.551299  56320814  56320652  Benign  
2           0           0  56319311.5  301.934596  56319525  56319098  Benign  
3           0           0         0.0    0.000000         0         0  Benign  
4           0           0         0.0    0.000000         0         0  Benign  

[5 rows x 80 columns]

In [3]:
df.count()

Dst Port         1048575
Protocol         1048575
Timestamp        1048575
Flow Duration    1048575
Tot Fwd Pkts     1048575
                  ...   
Idle Mean        1048575
Idle Std         1048575
Idle Max         1048575
Idle Min         1048575
Label            1048575
Length: 80, dtype: int64

In [4]:
df.describe()

Dst Port      Protocol  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  \
count  1.048575e+06  1.048575e+06   1.048575e+06  1.048575e+06  1.048575e+06   
mean   4.876262e+03  8.107557e+00   6.255555e+06  6.206622e+00  7.211191e+00   
std    1.444344e+04  4.460625e+00   1.260291e+09  4.447851e+01  1.048682e+02   
min    0.000000e+00  0.000000e+00  -9.190110e+11  1.000000e+00  0.000000e+00   
25%    2.200000e+01  6.000000e+00   7.000000e+00  1.000000e+00  1.000000e+00   
50%    5.300000e+01  6.000000e+00   1.023000e+03  2.000000e+00  1.000000e+00   
75%    4.430000e+02  6.000000e+00   4.066690e+05  7.000000e+00  6.000000e+00   
max    6.553300e+04  1.700000e+01   1.200000e+08  5.115000e+03  9.198000e+03   

       TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  \
count     1.048575e+06     1.048575e+06     1.048575e+06     1.048575e+06   
mean      4.479936e+02     4.521803e+03     1.745736e+02     8.389535e+00   
std       1.573541e+04     1.515021e+05     2.876713e+02     1.948279e+01   
min       0.000000e+00     0.000000e+00     0.000000e+00     0.000000e+00   
25%       0.000000e+00     0.000000e+00     0.000000e+00     0.000000e+00   
50%       3.600000e+01     5.500000e+01     3.400000e+01     0.000000e+00   
75%       4.550000e+02     7.680000e+02     1.990000e+02     0.000000e+00   
max       8.591554e+06     1.339773e+07     6.444000e+04     1.460000e+03   

       Fwd Pkt Len Mean  ...  Fwd Act Data Pkts  Fwd Seg Size Min  \
count      1.048575e+06  ...       1.048575e+06      1.048575e+06   
mean       3.879579e+01  ...       2.793536e+00      2.327970e+01   
std        5.331882e+01  ...       5.557106e+00      1.106185e+01   
min        0.000000e+00  ...       0.000000e+00      0.000000e+00   
25%        0.000000e+00  ...       0.000000e+00      2.000000e+01   
50%        2.566667e+01  ...       0.000000e+00      2.000000e+01   
75%        5.550000e+01  ...       4.000000e+00      3.200000e+01   
max        1.121703e+04  ...       1.031000e+03      4.800000e+01   

        Active Mean    Active Std    Active Max    Active Min     Idle Mean  \
count  1.048575e+06  1.048575e+06  1.048575e+06  1.048575e+06  1.048575e+06   
mean   5.152449e+04  2.136151e+04  8.789157e+04  3.995477e+04  3.101206e+06   
std    5.815586e+05  2.186405e+05  7.395725e+05  5.602693e+05  5.414780e+08   
min    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
25%    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
50%    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
75%    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
max    1.102401e+08  5.723446e+07  1.102401e+08  1.102401e+08  3.394503e+11   

           Idle Std      Idle Max      Idle Min  
count  1.048575e+06  1.048575e+06  1.048575e+06  
mean   7.297218e+05  4.812391e+06  2.126920e+06  
std    3.820031e+08  1.522117e+09  1.817013e+07  
min    0.000000e+00  0.000000e+00  0.000000e+00  
25%    0.000000e+00  0.000000e+00  0.000000e+00  
50%    0.000000e+00  0.000000e+00  0.000000e+00  
75%    0.000000e+00  0.000000e+00  0.000000e+00  
max    2.432682e+11  9.797810e+11  1.260300e+10  

[8 rows x 78 columns]

In [5]:
df.isnull().sum()

Dst Port         0
Protocol         0
Timestamp        0
Flow Duration    0
Tot Fwd Pkts     0
                ..
Idle Mean        0
Idle Std         0
Idle Max         0
Idle Min         0
Label            0
Length: 80, dtype: int64

In [6]:
df['Label'].value_counts()

Label
Benign            667626
FTP-BruteForce    193360
SSH-Bruteforce    187589
Name: count, dtype: int64

In [7]:
df.replace(to_replace=["FTP-BruteForce", "SSH-Bruteforce"], value="Malicious", inplace=True)

In [8]:
df['Label'].value_counts()

Label
Benign       667626
Malicious    380949
Name: count, dtype: int64

In [9]:
#label Encoding malicious=1 and bening=0
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
df['status'] = le.fit_transform(df['Label'])

In [10]:
df[['status','Label']].head(10)

status   Label
0       0  Benign
1       0  Benign
2       0  Benign
3       0  Benign
4       0  Benign
5       0  Benign
6       0  Benign
7       0  Benign
8       0  Benign
9       0  Benign

In [11]:
df=df.replace('NaN', float(np.nan), regex=True)

In [12]:
cleaned_data = df[[
    'Dst Port', 
    'Protocol',
    'Flow Duration',  
    'Tot Fwd Pkts', 
    'Tot Bwd Pkts',
    'Label',
    'status'
]]

In [13]:
cleaned_data.head(5)

Dst Port  Protocol  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts   Label  \
0         0         0      112641719             3             0  Benign   
1         0         0      112641466             3             0  Benign   
2         0         0      112638623             3             0  Benign   
3        22         6        6453966            15            10  Benign   
4        22         6        8804066            14            11  Benign   

   status  
0       0  
1       0  
2       0  
3       0  
4       0

In [14]:
sorted_data = cleaned_data.sort_values(by=['Flow Duration', 'Protocol'])

In [15]:
sorted_data.head(5)

Dst Port  Protocol  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts   Label  \
410958         0         0  -919011000000            81             0  Benign   
410957         0         0  -681402000000             3             0  Benign   
412184         0         0  -529801000000           505             0  Benign   
410959         0         0  -273850000000           282             0  Benign   
410956         0         0   -11873000000             2             0  Benign   

        status  
410958       0  
410957       0  
412184       0  
410959       0  
410956       0

In [16]:
sorted_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1048575 entries, 410958 to 904690
Data columns (total 7 columns):
 #   Column         Non-Null Count    Dtype 
---  ------         --------------    ----- 
 0   Dst Port       1048575 non-null  int64 
 1   Protocol       1048575 non-null  int64 
 2   Flow Duration  1048575 non-null  int64 
 3   Tot Fwd Pkts   1048575 non-null  int64 
 4   Tot Bwd Pkts   1048575 non-null  int64 
 5   Label          1048575 non-null  object
 6   status         1048575 non-null  int64 
dtypes: int64(6), object(1)
memory usage: 64.0+ MB


In [17]:
from sklearn.model_selection import train_test_split

In [18]:
X = sorted_data[['Dst Port', 'Protocol', 'Flow Duration', 'Tot Fwd Pkts', 'Tot Bwd Pkts']]
y = sorted_data['Label']

In [19]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [21]:
print("Scaled Feature:")
print(X_scaled[:5])

Scaled Feature:
[[-3.37611085e-01 -1.81758429e+00 -7.29210646e+02  1.68156284e+00
  -6.87643744e-02]
 [-3.37611085e-01 -1.81758429e+00 -5.40675544e+02 -7.20937748e-02
  -6.87643744e-02]
 [-3.37611085e-01 -1.81758429e+00 -4.20385024e+02  1.12142603e+01
  -6.87643744e-02]
 [-3.37611085e-01 -1.81758429e+00 -2.17296134e+02  6.20060103e+00
  -6.87643744e-02]
 [-3.37611085e-01 -1.81758429e+00 -9.42580737e+00 -9.45765519e-02
  -6.87643744e-02]]


In [22]:
import torch
from sklearn.preprocessing import LabelEncoder

In [23]:
#Convert to numerical
le = LabelEncoder()
y_encoded = le.fit_transform(y)

In [25]:
# PyTorch tensor
X_tensor_pt = torch.tensor(X_scaled, dtype=torch.float32)
y_tensor_pt = torch.tensor(y_encoded, dtype=torch.long)


In [27]:
print("PyTorch tensor:")
print(X_tensor_pt[:5])
print(y_tensor_pt[:5])

PyTorch tensor:
tensor([[-3.3761e-01, -1.8176e+00, -7.2921e+02,  1.6816e+00, -6.8764e-02],
        [-3.3761e-01, -1.8176e+00, -5.4068e+02, -7.2094e-02, -6.8764e-02],
        [-3.3761e-01, -1.8176e+00, -4.2039e+02,  1.1214e+01, -6.8764e-02],
        [-3.3761e-01, -1.8176e+00, -2.1730e+02,  6.2006e+00, -6.8764e-02],
        [-3.3761e-01, -1.8176e+00, -9.4258e+00, -9.4577e-02, -6.8764e-02]])
tensor([0, 0, 0, 0, 0])


In [30]:
import tensorflow as tf

# TensorFlow tensor convert
X_tensor = tf.convert_to_tensor(X_scaled, dtype=tf.float32)
y_tensor = tf.convert_to_tensor(y_encoded, dtype=tf.int64)

print("TensorFlow tensor:")
print(X_tensor[:5])
print(y_tensor[:5])


TensorFlow tensor:
tf.Tensor(
[[-3.3761108e-01 -1.8175843e+00 -7.2921063e+02  1.6815628e+00
  -6.8764374e-02]
 [-3.3761108e-01 -1.8175843e+00 -5.4067554e+02 -7.2093777e-02
  -6.8764374e-02]
 [-3.3761108e-01 -1.8175843e+00 -4.2038501e+02  1.1214260e+01
  -6.8764374e-02]
 [-3.3761108e-01 -1.8175843e+00 -2.1729613e+02  6.2006011e+00
  -6.8764374e-02]
 [-3.3761108e-01 -1.8175843e+00 -9.4258070e+00 -9.4576553e-02
  -6.8764374e-02]], shape=(5, 5), dtype=float32)
tf.Tensor([0 0 0 0 0], shape=(5,), dtype=int64)


In [31]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import TensorDataset, DataLoader

PYTORCH 

In [32]:
X_train, X_test, y_train, y_test = train_test_split(X_tensor_pt, y_tensor_pt, test_size=0.2, random_state=42)

# PyTorch TensorDataset and DataLoader 
train_dataset = TensorDataset(X_train, y_train)
train_loader = DataLoader(train_dataset, batch_size=64, shuffle=True)

In [33]:

class SimpleModel(nn.Module):
    def __init__(self, input_size, output_size):
        super(SimpleModel, self).__init__()
        self.fc1 = nn.Linear(input_size, 64)
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(64, output_size)
    
    def forward(self, x):
        x = self.fc1(x)
        x = self.relu(x)
        x = self.fc2(x)
        return x

input_size = X_train.shape[1]
output_size = len(torch.unique(y_train))
model = SimpleModel(input_size, output_size)


In [34]:
# Optimization and loss function 
optimizer = optim.Adam(model.parameters(), lr=0.001)
criterion = nn.CrossEntropyLoss()

In [35]:

# Training model
epochs = 10
for epoch in range(epochs):
    running_loss = 0.0
    for inputs, labels in train_loader:
        optimizer.zero_grad()
        outputs = model(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        running_loss += loss.item()
    print(f"Epoch {epoch+1}, Loss: {running_loss / len(train_loader)}")


Epoch 1, Loss: 0.15106282509107546
Epoch 2, Loss: 0.09786762145199417
Epoch 3, Loss: 0.07815449272097709
Epoch 4, Loss: 0.0656327350906552
Epoch 5, Loss: 0.05221448018126198
Epoch 6, Loss: 0.03687513591731712
Epoch 7, Loss: 0.022330383770077906
Epoch 8, Loss: 0.007320184807717924
Epoch 9, Loss: 0.006856500464308615
Epoch 10, Loss: 0.008586623290945854


In [36]:
# Evaluation model
model.eval()
with torch.no_grad():
    outputs = model(X_test)
    _, predicted = torch.max(outputs, 1)
    correct = (predicted == y_test).sum().item()
    total = y_test.size(0)
    accuracy = correct / total
    print(f"Test Accuracy: {accuracy}")

Test Accuracy: 0.9986076341701834


In [39]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test.numpy(), predicted.numpy())
print("Confusion Matrix:\n", cm)

Confusion Matrix:
 [[132968    290]
 [     2  76455]]


In [40]:
import pandas as pd
from sklearn.preprocessing import StandardScaler, LabelEncoder
import tensorflow as tf

TENSORFLOW

In [41]:
from keras.models import Sequential
from keras.layers import Dense, Input

model = Sequential([
    Input(shape=(input_size,)),  
    Dense(64, activation='relu'),
    Dense(output_size)  
])


In [42]:
optimizer = tf.keras.optimizers.Adam(learning_rate=0.001)
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [44]:
epochs = 10
for epoch in range(epochs):
    with tf.GradientTape() as tape:
        logits = model(X_tensor)
        loss_value = loss_fn(y_tensor, logits)
    grads = tape.gradient(loss_value, model.trainable_weights)
    optimizer.apply_gradients(zip(grads, model.trainable_weights))
    print(f"Epoch {epoch+1}, Loss: {loss_value.numpy()}")

Epoch 1, Loss: 0.6752879023551941
Epoch 2, Loss: 0.6694625616073608
Epoch 3, Loss: 0.6638022661209106
Epoch 4, Loss: 0.6583067178726196
Epoch 5, Loss: 0.6529760360717773
Epoch 6, Loss: 0.6478087902069092
Epoch 7, Loss: 0.6427993178367615
Epoch 8, Loss: 0.6379503607749939
Epoch 9, Loss: 0.6332553625106812
Epoch 10, Loss: 0.6287055015563965


In [46]:
X_test_tensor = tf.convert_to_tensor(X_test, dtype=tf.float32)
y_test_tensor = tf.convert_to_tensor(y_test, dtype=tf.int64)

In [47]:
model.compile(optimizer=optimizer, loss=loss_fn, metrics=['accuracy'])
loss, accuracy = model.evaluate(X_test_tensor, y_test_tensor, verbose=2)
print(f"Test Loss: {loss}")
print(f"Test Accuracy: {accuracy}")

6554/6554 - 3s - 470us/step - accuracy: 0.7910 - loss: 0.6243
Test Loss: 0.6242572665214539
Test Accuracy: 0.7910497784614563
